#pragma once
#define WIN_WIDTH 1920
#define WIN_HEIGHT 1080

#define DEFAULT_TILE_SIZE 64

#define RESOURCE_FOLDER "Resources"

#define TILE_MAP_FOLDER RESOURCE_FOLDER "/TileMaps/"
#define TILE_MAP_PATH(x) TILE_MAP_FOLDER x

#define DEFAULT_SAVE_PATH "Saves/"
#define DEFAULT_QUICKSAVE_FILE_NAME "QuackSwack"
#define FILE_EXTENSION ".yay"

#define TILEMENU_X_AREA 5
#define TILEMENU_Y_AREA 20
#define TILEMENU_BORDER_SIZE 8
#define TILEMENU_WIDTH (DEFAULT_TILE_SIZE * TILEMENU_X_AREA) + (TILEMENU_BORDER_SIZE * 2)

#define TILE_LAYER_AMOUNT 3
#define LAYER_AMOUNT 4

#define HITBOX_ID_START 500
#define NR_OF_HITBOXES 3
#define HITBOX_LAYER 3

#define MENU_BAR_HEIGHT 20
#define TOTAL_BAR_HEIGHT MENU_BAR_HEIGHT

#define MAXIMUM_WORKSPACE 10000