#pragma once
#define WIN_WIDTH 1280
#define WIN_HEIGHT 720

#define DEFAULT_TILE_SIZE 32

#define RESOURCE_FOLDER "Resources"

#define TILE_MAP_FOLDER RESOURCE_FOLDER "/TileMaps/"
#define TILE_MAP_PATH(x) TILE_MAP_FOLDER x

#define BUTTON_TEXTURE_FOLDER RESOURCE_FOLDER "/Buttons/"
#define BUTTON_TEXTURE_PATH(x) BUTTON_TEXTURE_FOLDER x

#define FILE_EXTENSION ".yay"

#define TILEMENU_X_AREA 5
#define TILEMENU_Y_AREA 20
#define TILEMENU_BORDER_SIZE 8
#define TILEMENU_WIDTH (DEFAULT_TILE_SIZE * TILEMENU_X_AREA) + (TILEMENU_BORDER_SIZE * 2)

#define IMAGE_BAR_HEIGHT 40
#define MENU_BAR_HEIGHT 20
#define TOTAL_BAR_HEIGHT IMAGE_BAR_HEIGHT + MENU_BAR_HEIGHT
